export { ReactComponent as Mascot } from './mascot.svg';
export { ReactComponent as Woman } from './woman.svg';
export { ReactComponent as Boy } from './boy.svg';
export { ReactComponent as Man } from './man.svg';
export { ReactComponent as WomanSmile } from './woman-smile.svg';
export { ReactComponent as Fireman } from './fireman.svg';
export { ReactComponent as Police } from './police.svg';
export { ReactComponent as SecurityMan } from './security-man.svg';
export { ReactComponent as ManSmile } from './man-smile.svg';
